import turtle as t


t.pencolor("black")

t.penup()
t.goto(-200, -200)
t.pendown()
t.speed(10)
t.colormode(255)


a = 600
a2 = 2*a
t.hideturtle()


def house():
    t.fillcolor(169, 169, 169)
    t.begin_fill()
    for i in range(2):
        t.forward(a)
        t.left(90)
        t.forward(a/3.5)
        t.left(90)
    t.end_fill()
    t.forward(a/2)
    t.left(90)
    t.forward(a/3.5)
    t.penup()
    t.goto(-200, -200)
    t.pendown()
    t.right(90)
    t.forward(a/8)
    t.left(90)
    t.fillcolor(139, 69, 19)
    t.begin_fill()
    t.forward((a/3.8)-10)
    t.right(90)
    t.forward(a/3.8)
    t.right(90)
    t.forward((a/3.8)-10)
    t.right(180)
    t.end_fill()
    for x in range(10):
        t.forward(a/46)
        t.left(90)
        t.forward((a/3.8))
        t.back((a/3.8))
        t.right(90)
    t.penup()
    t.goto(-200, -200)
    t.pendown()
    t.right(90)
    t.forward(a/2)
    t.forward(a/10)
    t.left(90)
    t.penup()
    t.forward(a/46)
    t.pendown()
    t.fillcolor(173, 216, 230)
    t.begin_fill()
    for y in range(2):
        t.forward(a/6)
        t.right(90)
        t.forward(a/16)
        t.right(90)
    t.end_fill()
    t.left(180)
    t.penup()
    t.forward(a/46)
    t.pendown()
    t.left(90)
    t.forward(a/10)
    t.left(90)
    t.fillcolor(139, 69, 19)
    t.begin_fill()
    for n in range(2):
        t.forward(a/6)
        t.right(90)
        t.forward(a/12)
        t.right(90)
    t.end_fill()
    t.right(90)
    t.penup()
    t.forward(a/12)
    t.back(a/86)
    t.left(90)
    t.forward(a/12)
    t.pendown()
    t.fillcolor(255, 255, 255)
    t.begin_fill()
    t.circle(a/160)
    t.end_fill()
    t.penup()
    t.back(a/12)
    t.right(90)
    t.pendown()
    t.forward(a/86)
    t.forward(a/24)
    t.left(90)
    t.penup()
    t.forward(a / 46)
    t.pendown()
    t.fillcolor(173, 216, 230)
    t.begin_fill()
    for y in range(2):
        t.forward(a / 6)
        t.right(90)
        t.forward(a / 16)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-200, -200)
    t.pendown()
    t.forward(a/3.5)
    t.right(90)
    t.fillcolor(169, 169, 169)
    t.begin_fill()
    for i in range(2):
        t.forward(a)
        t.left(90)
        t.forward(a/4)
        t.left(90)
    t.end_fill()
    t.fillcolor(173, 216, 230)
    t.begin_fill()
    t.forward(a / 4)
    t.left(90)
    t.forward(a / 4)
    t.back(a/4)
    t.right(90)
    t.forward(a/2)
    t.left(90)
    t.forward(a/4)
    t.back(a/4)
    t.right(90)
    t.forward(a / 4)
    t.left(90)
    t.forward(a / 4)
    t.back(a / 4)
    t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-200, -200+a/3.5)
    t.pendown()
    t.forward(a/22)
    t.left(90)
    t.begin_fill()
    for y in range(2):
        t.forward(a / 6)
        t.right(90)
        t.forward(a / 16)
        t.right(90)
    t.end_fill()
    t.right(90)
    t.forward(a/16)
    t.forward(a/32)
    t.left(90)
    t.begin_fill()
    for y in range(2):
        t.forward(a / 6)
        t.right(90)
        t.forward(a / 16)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-200, -200+a/3.5)
    t.pendown()
    t.right(90)
    t.forward(a/4)
    t.forward(a/2)
    t.forward(a / 22)
    t.left(90)
    t.begin_fill()
    for y in range(2):
        t.forward(a / 6)
        t.right(90)
        t.forward(a / 16)
        t.right(90)
    t.end_fill()
    t.right(90)
    t.forward(a / 16)
    t.forward(a / 32)
    t.left(90)
    t.begin_fill()
    for y in range(2):
        t.forward(a / 6)
        t.right(90)
        t.forward(a / 16)
        t.right(90)
    t.end_fill()
    t.penup()
    t.goto(-200, -200 + a / 3.5)
    t.pendown()
    t.right(90)
    t.forward(a/4)
    t.forward(a/12)
    t.left(90)
    t.begin_fill()
    for i in range(2):
        t.forward((a/4)-20)
        t.right(90)
        t.forward(a/3)
        t.right(90)
    t.end_fill()
    t.right(90)
    t.forward(a/6)
    t.left(90)
    t.forward((a/4)-20)
    t.back((a/4)-20)
    t.left(90)
    t.forward(a/46)
    t.right(90)
    t.penup()
    t.forward(a/18)
    t.pendown()
    t.pencolor(255, 255, 255)
    t.pensize(2)
    t.forward(a/24)
    t.pencolor(0, 0, 0)
    t.pen()
    t.penup()
    t.back((a/18)+(a/24))
    t.right(90)
    t.forward(a/46)
    t.forward(a/46)
    t.left(90)
    t.penup()
    t.forward(a / 18)
    t.pendown()
    t.pencolor(255, 255, 255)
    t.pensize(2)
    t.forward(a / 24)
    t.pencolor(0, 0, 0)
    t.pensize(1)
    t.penup()
    t.back((a / 18) + (a / 24))
    t.goto(-200, -200+a/3.5)
    t.pendown()
    t.forward(a/4)
    t.fillcolor(0, 0, 0)
    t.begin_fill()
    t.left(80)
    t.forward(a/8)
    t.right(170)
    t.forward((a-a/8)-1)
    t.right(90)
    t.forward((a/48)+1)
    t.left(90)
    t.end_fill()
    t.penup()
    t.goto(-200, -200+a/3.5)
    t.pendown()
    t.forward(a/2+a/4)
    t.left(90)
    t.forward(a/4)
    t.fillcolor(169, 169, 169)
    t.begin_fill()
    t.forward(a/4)
    t.right(90)
    t.forward(a/4)
    t.right(90)
    t.forward(a/4)
    t.end_fill()
    t.right(180)
    t.penup()
    t.forward(a/5.5)
    t.left(90)
    t.forward((a/4)/2)
    t.pendown()
    t.fillcolor(173, 216, 230)
    t.begin_fill()
    t.circle((a/4)/4)
    t.end_fill()
    t.left(90)
    t.penup()
    t.forward((a/4)/4)
    t.pendown()
    t.left(90)
    t.forward((a/4)/4)
    t.back(((a/4)/4)*2)
    t.forward((a/4)/4)
    t.left(90)
    t.forward((a/4)/4)
    t.back(((a/4)/4)*2)
    t.penup()
    t.goto(-200+a, -200+a/3.5+a/4)
    t.pendown()
    t.forward(a/4)
    t.fillcolor(0, 0, 0)
    t.begin_fill()
    t.right(80)
    t.forward(a/8)
    t.left(170)
    t.forward(a/2.9+17)
    t.left(90)
    t.forward((a/48)+1)
    t.end_fill()


if __name__ == "__main__":
    house()


t.exitonclick()
t.mainloop()
